name: Ejecutar búsqueda con SerpAPI

on:
  workflow_dispatch:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Ejecutar script
      env:
        SERPAPI_KEY: ${{ secrets.SERPAPI_API_KEY }}
      run: python3 googletoexcel.py

    - name: Subir archivo de resultados
      uses: actions/upload-artifact@v3
      with:
        name: Resultados_excel
        path: resultados_busqueda.xlsx
